### ISSUE TITLE
Request: Fire Embelm Fates (eur)

### ISSUE THREAD

**Issue by Schtenk** [ihaveamac/9.6-dbgen-xmls#14]
If you don't take requests, Im sorry, but can you make a dbgen xml for Fire Emblem Fates (european) if it is possible, I would very much appreciate it.

**Comment by ihaveamac** [comment]
there's multiple versions of this I think (birthright, conquest, special edition?), so which one do you need? I'll probably do the others after that.

**Comment by ihaveamac** [comment]
they're probably going to have the same XML anyway(at least birthright+conquest), much like the USA versions. @luigoalma said he's going to do it.

**Comment by Schtenk** [comment]
Thank you for the fast response :D
Im not entirely sure since there is only one version on the eshop. But what i understand is that you choose between birthright and conquest a bit into the eshop version and then are able to buy the other versions as dlc later.

**Comment by luigoalma** [comment]
[FEF_EUR.zip](https://github.com/ihaveamac/9.6-dbgen-xmls/files/297937/FEF_EUR.zip)

**Comment by Schtenk** [comment]
Thanks again for the fast responses, I tried using the xml you provided in the zip but they don't seem to work :(

**Comment by ihaveamac** [comment]
"don't seem to work" what happens when you try? red/yellow screen?

**Comment by Schtenk** [comment]
sorry should have been more specific, HANS get stuck on red

**Comment by ihaveamac** [comment]
are you sure the XMLs were in the "mmap" folder? also note that HANS doesn't support 9.6-crypto titles at the moment.

**Comment by ihaveamac** [comment]
actually when does the red screen happen? can you use other things like svdt?

**Comment by Schtenk** [comment]
The red screen happens almost instanly when I choose FE:Fates in the title selector, it's the same with svdt,  I have tried using HANS on MyNintendo Picross: The Legend of Zelda: Twilight Princess which goes to the HANS menu with the xml and red screens without

**Comment by ihaveamac** [comment]
XMLs look a bit odd, only having a single entry compared to three like the USA ones...

**Comment by ihaveamac** [comment]
I've got no idea what is happening here :/ the codebins for USA seem to have a very similar size to EUR.

maybe worth trying the USA one?

https://github.com/ihaveamac/9.6-dbgen-xmls/blob/master/mmap/0004000000179400.xml
rename it to 0004000000179500.xml (Birthright) or 0004000000179700.xml (Conquest) depending on which one you're using and see if it does anything different.

**Comment by luigoalma** [comment]
@Schtenk, do you have any cia manager? Because I need confirmation on the title id, I suspect that the eshop version has its own title id.

**Comment by Schtenk** [comment]
I tried renaming that file to both 0004000000179500.xml and 0004000000179700.xml which had the same result, i also tried renaming it to 000400000017A800 (eur special edition) and 0004000000179800(us special edition) and got the same result

**Comment by Schtenk** [comment]
Sadly i do not have any cia managers :(

**Comment by ihaveamac** [comment]
what's your system version, and are you using custom firmware?

**Comment by Schtenk** [comment]
im on 11.0.0-33, using super mystery dungeon as entry point

**Comment by ihaveamac** [comment]
I'm currently not sure at the moment, sorry. I'll leave this issue open until I can figure it out.

**Comment by Schtenk** [comment]
there aren't any way i can check the title id on the firmware im on?

**Comment by luigoalma** [comment]
Actually, @Schtenk, try one more title id, try renaming one of the xmls of the zip to 000400000017A400

**Comment by ihaveamac** [comment]
FBI 2.x might still work to list titles. please try it out. https://github.com/Steveice10/FBI/releases

**Comment by Schtenk** [comment]
YES, i got into HANS menu when renaming one of the files from the zip @luigoalma provided to 000400000017A400

**Comment by ihaveamac** [comment]
so I was not aware of this, but apparently the digital version of "Fire Emblem: Fates" is sold as a single game in the EUR region, and as two separate games for retail. in the USA, both versions are sold separately at retail and the eShop. this is why I was confused.

anyway, good to hear that it works now. @luigoalma will probably add the XML to the repo soon.
