### ISSUE TITLE
Some games freezes on a yellow screen evein with the right xml

### ISSUE THREAD

**Issue by Filo97** [ihaveamac/9.6-dbgen-xmls#15]
https://gbatemp.net/threads/haxx-2-7-doesnt-allow-9-6-crypto-target-titles-even-with-the-right-xml.432896/#post-6495453

I personally tested with kirby planet robobot and BOXBOY! but in that thread there is also another user who tried. i am using n3ds xl 11.0.0-33E basehaxx

**Comment by ihaveamac** [comment]
https://github.com/ihaveamac/9.6-dbgen-xmls#i-keep-getting-a-yellow-screen-when-trying-to-use-a-96-title

this was a problem with "Citizens of Earth" too, which doesn't use 9.6-crypto. a custom XML had to be created for this one. so the same might be required for these games, or anything that crashes on a yellow screen.

**Comment by Filo97** [comment]
Do you know how to fix them?

**Comment by ihaveamac** [comment]
custom xml for each game with the yellow screen issue is the only way I see at the moment, aside from seeing why *hax's default addresses are sometimes wrong. that's not exactly easy to do, so...

**Comment by Filo97** [comment]
I hope it gets fixed... i guess i will close it here, but, i hope the custom .xml will be made...
