### ISSUE TITLE
How do I use the XML files?

### ISSUE THREAD

**Issue by rpalmon** [ihaveamac/9.6-dbgen-xmls#16]
How do I use the XML files so I can use it on svdt (save data manager) and get the save files of the games that I want and modify it?

**Comment by gnmmarechal** [comment]
Get a compatible build of HBL (1.1) and place the xml files under sdmc:/mmap .

**Comment by rpalmon** [comment]
Can you link me a download link to HBL 1.1?

**Comment by gnmmarechal** [comment]
https://citizens.salthax.org/boot.3dsx

**Comment by ihaveamac** [comment]
don't forget `new_boot.3dsx` in the repo is the exact same thing.
