### ISSUE TITLE
Tutorial on how to generate XML files for games?

### ISSUE THREAD

**Issue by rpalmon** [ihaveamac/9.6-dbgen-xmls#17]
Hello, I want to be able to create an XML file for a game that I have but I am not good at following text based tutorials. Can someone make a video tutorial on how to make one as it is easier to follow along or at least link me to one? Thanks.

**Comment by ihaveamac** [comment]
this doesn't feel like something suitable for a video tutorial imo. what part of [the written tutorial at the wiki](https://github.com/ihaveamac/9.6-dbgen-xmls/wiki) are you having problems with?
