### ISSUE TITLE
Kirby Robobot Crash

### ISSUE THREAD

**Issue by timbiotic** [ihaveamac/9.6-dbgen-xmls#18]
I downloaded the MMAP into an MMAP folder on my SD card and tried both jk and svdt.  Both crash yellow.  Is it possible https://github.com/ihaveamac/9.6-dbgen-xmls/blame/5d0be2ba11541b4168d74066818b341e498437fc/mmap/0004000000183600.xml is not correct?  Or am I missing something.

**Comment by ihaveamac** [comment]
https://github.com/ihaveamac/9.6-dbgen-xmls#i-keep-getting-a-yellow-screen-when-trying-to-use-a-96-title
