### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by ltlynx** [ihaveamac/9.6-dbgen-xmls#19]
I may ask you for the xml archives for two games:
- Super Mario Bros. Deluxe (EUR) - 00040000000FFB00
- The Legend of Zelda: Link's Awakening DX (EUR) - 0004000000042A00

Also, could you do Shantae games' ones?
Thanks.

**Comment by ihaveamac** [comment]
are these games giving you yellow screens or red?

**Comment by nanashi89** [comment]
Can you do xmls archives for the following 3 games?
Shin Megami Tensei IV Apocalypse 
Rabbids in Time
Radio Hammer

All 3 are from the US version.

**Comment by ihaveamac** [comment]
do these give you red or yellow screens when you attempt to use them under *hax?

**Comment by nanashi89** [comment]
Rabbids 3D gives me a yellow screen.
SMT IV Apocalypse gives me a red screen.
And Radiohammer gives me a red screen.

**Comment by ihaveamac** [comment]
yellow screen requires more effort than just generating an xml, it needs to be manually edited too. I don't really have the time or patience to create one for each game with a yellow screen.

the ones with red screens have missing XMLs probably.

**Comment by nanashi89** [comment]
So can you do SMT IV Apocalypse and Radiohammer?

**Comment by ihaveamac** [comment]
probably.

**Comment by SirSoup** [comment]
Can you do I station Z?
its a red screen

**Comment by SirSoup** [comment]
Ice station Z*

**Comment by nanashi89** [comment]
The legit copy of Pokemon Sun and Moon comes out next week. Now that a leaked copy of Sun has surfaced, can you create an xml for Sun?

And how's the xml for RadioHammer coming?

**Comment by ihaveamac** [comment]
> The legit copy of Pokemon Sun and Moon comes out next week. Now that a leaked copy of Sun has surfaced, can you create an xml for Sun?

it is probably the same as moon (try copying and renaming the XML). I was planning on uploading a bunch on s/m's release date (less work for me!)

> And how's the xml for RadioHammer coming?

forgot about doing it

on another note, please see https://twitter.com/smealum/status/795397482364551169.

**Comment by ihaveamac** [comment]
Pokémon Sun is up, though it was just identical to Moon.

Radiohammer USA is pretty annoying to find so it might take time. or just wait for smealum to bypass the seeddb crypto (which would make this repo no longer needed).

**Comment by RSAC1997** [comment]
Excuse me, I want to use JK save manager from homebrew but when i load Pokemon Sun it shows a red screen. I already read you uploaded the xml to fix this, but could you explain me how to do it and where to find it?

**Comment by RSAC1997** [comment]
i downloaded the xmls via the homebrew app, now it works. Thank you

**Comment by arkiek** [comment]
can i request yokai watch 2 bony spirits/fleshy souls EU?
Bony Spirits (000400000019B000)
Fleshy souls (000400000019B100)

**Comment by AlteredCybody** [comment]
Oh my bad for the main post comment, sorry! (would you like me to take down my com'?)

So I need a custom memmap for Pokémon Picross EU. Is there any other information you need?

Thank you very much~
