### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ChrisMuncey** [ihaveamac/9.6-dbgen-xmls#20]
I couldn't figure out for the life of me how to make a pull request, so I posted here, sorry if this is wrong. I would like to request a set of games please though.

Pokemon: Omega Ruby (USA) ( 000400000011C400 )
Pokemon: Alpha Sapphire (USA) ( 000400000011C500 )

I don't actually have Omega Ruby, but Alpha Sapphire gives a yellow screen.

Sorry again if this is the wrong place for this, and sorry if these games are in the file currently, and I'm just too dumb to find them.

**Comment by ihaveamac** [comment]
these games have PASLR added in 11.1.0-X; generating XMLs for them won't do anything. *hax needs to be updated to support these titles.

if you need to access Pokémon Omega Ruby/Alpha Sapphire, use a special build of JKSM + Pokémon Bank.

https://gbatemp.net/threads/release-jks-savemanager-homebrew-cia-save-manager.413143/page-99#post-6701558

put JKSM.3dsx and JKSM.xml (from https://raw.githubusercontent.com/J-D-K/JKSM/cleanup/JKSM.xml) in /3ds/JKSM, choose "Pokémon Bank", then find X/Y/OR/AS.
