### ISSUE TITLE
[Question] Do you have a list of games?

### ISSUE THREAD

**Issue by luigoalma** [ihaveamac/9.6-dbgen-xmls#3]
I want to help but I would like to know if you're using a list of games with the 9.6+ crypto or any list in general that allows you to know with games need to be added.

**Comment by ihaveamac** [comment]
most of it is kind of by memory, however you could take a look at http://pastebin.com/zNM8zYwa which is a list of seeds in a seeddb.bin (on a site that's currently down)

if the game has a game card version, the code of it would match in both the digital/9.6-encrypted title and the game card, so you could use that if you want.

**Comment by luigoalma** [comment]
Ok, thanks, this will make it easier to add titles to the list, but I'm not going to be that active adding titles because I have to study and stuff like that.
I'll close this issue now.
